networks:
  private:
services:

  backend:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    networks:
      - private

  mysql:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - private
  phpmyadmin:
    image: phpmyadmin:5.2
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - private